- bower.json
- test/Main.purs
Bump `purescript-strings` to allow compilation with current compiler (orphan instance).
> Bump versions

- src/Text/Parsing/StringParser/String.purs
Fixes two typos. We don't want to match `n` and `r` as whitespace :smile:
> Fix white space characters in `whiteSpace`

- bower.json
So this package builds on its own, but if you were to have a package that has
this one as its only dependency, it fails to build because it's missing the
packages this commit includes.
> Add some needed dependencies explicitly

- bower.json
- src/Text/Parsing/StringParser/Combinators.purs
- test/Main.purs
Rebased version of #21 (thanks @nwolverson!)
Resolves #21, resolves #9.
> Use MonadRec for many

- bower.json
- src/Text/Parsing/StringParser/String.purs
- test/Main.purs
Add regex and regex' as discussed in issue https://github.com/purescript-contrib/purescript-string-parsers/issues/25.
> Add a regex combinator

- src/Text/Parsing/StringParser/Combinators.purs
- test/Main.purs
Ran into this the other day with a really long string. Maybe some of the other methods might be useful to look into, but the `many` implementation already uses `manyRec` and whatnot.
I also tried to use untilM' from monad-rec-loops but on my desktop, it's just way too slow (average ~8x slower):
normal:
```
C:\Users\justin\Code\purescript-string-parsers [fix-manyTill-overflow ≡]> Measure-Command {pulp test}
* Building project in C:\Users\justin\Code\purescript-string-parsers
* Build successful.
* Running tests...
* Tests OK.
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 102
Ticks             : 21023247
TotalDays         : 2.43324618055556E-05
TotalHours        : 0.000583979083333333
TotalMinutes      : 0.035038745
TotalSeconds …
```
> fix overflow caused by manyTill implementation

- src/Text/Parsing/StringParser.purs
- test/Main.purs
Hi,
I'm enjoying this library quite a bit, but I kept wishing there was a `Semigroup` instance for `Parser a` where `a` is a `Semigroup`, like there is in purescript-parsing, so I figured why not make a PR? 
I've added the instance and I modified the `tryTest` in the tests to use Semigroup syntax, which is a bit nicer.
I really appreciate all of the effort that has been put into this library, and I hope this is helpful!
> added Semigroup instance for Parser a where a is a Semigroup

- src/Text/Parsing/StringParser/CodePoints.purs
- test/CodePoints.purs
`CodePoint.anyChar` was not unicode-safe. I think it would be good to add a `CodePoint.anyCodePoint` parser too (I'll add that in a separate PR), but `CodePoint.anyChar` seems to be valuable as well.
> Fix CodePoint.anyChar parser

- README.md
- test/Examples.purs
Fixes #51.
While adding CI would be nice, this is at least better than what we have now.
> Port learning repo's syntax examples to this repo

- src/Text/Parsing/StringParser.purs
Fixes #33
Note: this doesn't implement `Foldable` for Parser, which is the other part of that issue.
> Add a Monoid instance for Parser

- src/Text/Parsing/StringParser.purs
- src/Text/Parsing/StringParser/CodeUnits.purs
> Improve default error

- .github/workflows/ci.yml
- src/Text/Parsing/StringParser/CodePoints.purs
- test/CodePoints.purs
- test/Examples.purs
- test/Main.purs
Reverts #59.
---
**Checklist:**
> Revert #59

- CHANGELOG.md
This PR updates the CHANGELOG in preparation for the upcoming release of this library.
Related: purescript/purescript#3985
> Update changelog since v5.0.1

- CHANGELOG.md
- spago.dhall
- test/Examples.purs
Fixes spago warnings when building and running tests for this library locally.
---
**Checklist:**
> Fix transitive dependencies errors in spago 0.20.0

- CHANGELOG.md
- test/CodePoints.purs
- test/CodeUnits.purs
When I first ran tests locally in this repo, my system stalled for a minute at 100% CPU, which made me think something was wrong. Not sure if this is a real problem, or if parsing is just really slow for the stack overflow tests.
This PR moves the slower stack overflow tests to the end of each suite and prints some status messages to users.
```
time spago test                                                       
Compiling Test.Main
Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
[info] Build succeeded.
Testing CodePoint parsing
Running basic tests
Running overflow tests (may take a while)
Testing CodeUnit parsing
Running basic tests
Running overflow tests (may take a while)
[info] Tests succeeded.
spago test  122.84s user 1.35s system …
```
> Run slowest tests last and print status updates

- .gitignore
- CHANGELOG.md
- README.md
- bench/Main.purs
- spago.dhall
I added a benchmark module akin to the one from `parsing`. May help in validating a fix for https://github.com/purescript-contrib/purescript-string-parsers/issues/77 and keep track of performance further down the line. @jamesdbrock 
---
**Checklist:**
> Add a simple benchmark module

- src/Text/Parsing/StringParser.purs
> Update docs to refer to CodeUnit-based inxed

- .gitignore
- CHANGELOG.md
- src/Text/Parsing/StringParser/CodePoints.purs
- src/Text/Parsing/StringParser/CodeUnits.purs
- test/CodePoints.purs
- test/CodeUnits.purs
> Fix regex anchor #69

- CHANGELOG.md
- bench/Main.purs
- spago.dhall
- src/Text/Parsing/StringParser/Combinators.purs
- test/BasicSpecs.purs
- test/Main.purs
- test/Utils.purs
This project could do with a more structured and comprehensive set of tests. This might especially come in handy when we want to make some fundamental changes in the near future.
@jamesdbrock I encountered some things I've flagged with `TODO` in the diff. Should we
```
, { name: "sepEndBy"
, parser: mkAnyParser $ sepEndBy anyLetter (char ';')
-- TODO: ";" should be parsed successfully
, inputs: { successes: [ "", "a", "a;b", "a;b;c", "a;" ], failures: [ ";", ";a", "ab", "a;ab" ] }
}
, { name: "endBy"
, parser: mkAnyParser $ endBy anyLetter (char ';')
-- TODO: ";" should be parsed successfully
, inputs: { successes: [ "", "a;", "a;b;", "a;b;c;" ], failures: [ "a", ";", ";a", "ab", "a;b", "a;b;c" ] }
}
```
**Checklist:**
> Add basic spec tests

- CHANGELOG.md
- bench/Main.purs
- src/Text/Parsing/StringParser.purs
- src/Text/Parsing/StringParser/CodePoints.purs
- src/Text/Parsing/StringParser/CodeUnits.purs
- src/Text/Parsing/StringParser/Combinators.purs
- test/CodePoints.purs
- test/Examples.purs
- test/Main.purs
Proof of concept to fix #77. This change would be breaking because it changes the underlying representation.
| Benchmark before | Benchmark after |
|:---:|:---:|
| StringParser.runParser parse23AnyCharPoints | StringParser.runParser parse23AnyCharPoints |
| mean   = 1.01 s | mean   = 16.14 ms |
| stddev = 51.48 ms | stddev = 13.64 ms |
| min    = 963.28 ms | min    = 8.55 ms |
| max    = 1.16 s | max    = 53.29 ms |
| StringParser.runParser parse23AnyCharUnits | StringParser.runParser parse23AnyCharUnits |
| mean   = 8.53 ms | mean   = 8.73 ms |
| stddev = 2.77 ms | stddev = 2.95 ms |
| min    = 7.25 ms | min    = 7.24 ms |
| max    = 38.72 ms | max    = 40.49 ms |
| StringParser.runParser parse23DigitPoints | StringParser.runParser parse23DigitPoints |
| mean   = 994.93 ms | mean   = …
> Use slices instead of cursors

- CHANGELOG.md
- spago.dhall
- src/Text/Parsing/StringParser/CodePoints.purs
- test/BasicSpecs.purs
- test/CodePoints.purs
> Add basic code point parsers
